- name: Pre-install python
  hosts: all
  gather_facts: false
  pre_tasks:
  - name: Install python2 and python3 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt-get install -qqy python3-minimal 'python2.*-minimal')"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  become: yes

- name: Pre-deploy tasks
  hosts: all
  roles:
<% if (typeof LA_etc_hosts != 'undefined') { %>
    - { role: ypsman.hosts, tags: ["pre-task-etc-hosts"]}
<% } %>
    - { role: weareinteractive.sudo, tags: ["pre-task-sudo"] }
    - pre_deploy
  become: yes

- name: Pre-deploy solr tasks
  hosts: solr7-server
  roles:
    - solr_pre_deploy
  become: yes
