# Playbooks for hub-csic

- name:  biocache-hub-csic
  hosts:  biocache-hub-csic
  roles:
    - common
    - java
    - webserver
    - tomcat
    - i18n
    - { role: biocache-hub, biocache_hub_artifact: ala-hub, biocache_hub: csic-hub, grouped_facets_json: grouped_facets_ala.json
    # grouped_facets_json: {{inventory_dir}}/files/grouped_facets_csic.json,
    # overlays_json: {{inventory_dir}}/files/overlays-csic.json,
    }

- name: branding-csic
  hosts: branding-csic
  roles:
    - common
    - webserver
    - branding

- name: bie-hub-csic
  hosts: bie-hub-csic
  roles:
    - common
    - java
    - webserver
    - tomcat
    - i18n
    - nameindex
    - { role: bie-hub, bie_hub: csic-bie-hub, bie_hub_artifact: ala-bie }

- name: regions-csic
  hosts: regions-csic
  roles:
    - common
    - java
    - webserver
    - tomcat
    - i18n
    - { role: regions, regions: regions-csic,
    # menu_config_json: {{inventory_dir}}/files/menu-config-csic.json
    }

