
[biocache-hub-csic]



[branding-csic]



[bie-hub-csic]



[regions-csic]




[hub-csic:children]

biocache-hub-csic
branding-csic
bie-hub-csic
regions-csic

[hub-csic:vars]

# used in biocache and bie hubs
biocache_query_context =  data_hub_uid:dh1

# used in regions
enable_query_context = true
query_context =  data_hub_uid:dh1
hub_filter =  data_hub_uid:dh1
enable_hub_data = true

orgNameLong = 
orgNameShort = csic

header_and_footer_baseurl = http://
header_and_footer_version = 2

orgCity = Camberra
orgStateProvince = ACT
orgPostcode = 2601
orgCountry = Australia

orgPhone=
orgFax=
orgPhone=
org_url = http://

###### favicon #######
favicon_url=https://raw.githubusercontent.com/living-atlases/artwork/master/favicon.ico
skin_favicon=https://raw.githubusercontent.com/living-atlases/artwork/master/favicon.ico

biocache_hub_hostname = 
biocache_hub_url = http://
biocache_hub_base_url = http://
biocache_hub_context_path = 
biocache_base_url = http://

use_ala_bie=true
use_ala_image_service=true
use_ala_spatial_portal=true

bie_hub_base_url = http://
bie_hub_hostname = 
bie_hub_context_path = 
bie_base_url = http://
regions_base_url = http://
regions_hostname = 
regions_context_path = 

explore_url = http:///explore/your-area/
regions_explore_url = http://
regions_map_bounds = []
# Only used in regions
biocache_records_url = http://

explore_your_area_lat = 16.942
explore_your_area_lng = 1.261
explore_your_area_location = Australia

map_default_latitude = 16.942
map_default_longitude = 1.261
map_default_zoom = 5
zoom_outside_scoped_region = false

skin_home_url = http://
ala_base_url = http://

skin_taxa_links_base_url = http:///species/

ssl_certificate_server_dir=/etc/ssl
ssl_cert_file=certs/ssl-cert-snakeoil.pem
ssl_key_file=private/ssl-cert-snakeoil.key

[branding-csic:vars]

branding_hostname = 
branding_url = 
branding_path = /

[biocache-hub-csic:vars]

skin_layout = ala

[bie-hub-csic:vars]

bie_skin_layout = ala

[regions-csic:vars]

regions_skin_layout = main

# TODO bie and biocache base url is different

