- name: Post-deploy tasks
  hosts: all
  roles:
    - post_deploy
  become: yes

- name: Post-deploy postfix tasks
  hosts: biocache-hub, cas-servers
  vars:
    postfix_aliases:
      - user: root
        alias: support@living-atlas-of-wakanda.org
    postfix_relayhost: mail.living-atlas-of-wakanda.org
    postfix_relaytls: true
    postfix_sasl_user: 'support@living-atlas-of-wakanda.org'
    postfix_sasl_password: 'SOME_PASSWORD'
    postfix_relayhost_port: 587
    postfix_smtpd_relay_restrictions: ['permit_mynetworks', 'permit_sasl_authenticated', 'defer_unauth_destination']
  roles:
    - { role: oefenweb.postfix, tags: ["post-task-postfix"] }
  become: yes
