# Addionial LA pre deploy tasks

# https://github.com/AtlasOfLivingAustralia/documentation/wiki/Before-Start-Your-LA-Installation#solr-limits

- name: Add nofile limits for solr domain hard
  pam_limits:
    domain: 'solr'
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: 'hard', limit_item: 'nofile', value: 65535 }
    - { limit_type: 'soft', limit_item: 'nofile', value: 65535 }
    - { limit_type: 'hard', limit_item: 'nproc', value: 65535 }
    - { limit_type: 'soft', limit_item: 'nproc', value: 65535 }
  tags: pre-task-solr-limits

- name: reload settings from all system configuration files
  shell: sysctl --system
  tags: pre-task-solr-limits
